In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
import librosa

dataset_path = "/content/drive/MyDrive/MINIPROJECT/yassen_filtered/train"

valid_files = []
null_count = 0
for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.endswith(".wav"):
            path = os.path.join(root, file)
            try:
                signal, sr = librosa.load(path, sr=None)

                if len(signal) > 0:
                    valid_files.append(path)
                else:
                    null_count += 1
                    print("Empty audio removed:", path)

            except:
                null_count += 1
                print("Corrupted file removed:", path)



import hashlib

unique_files = []
hashes = set()
duplicate_count = 0

for file in valid_files:
    with open(file, "rb") as f:
        file_hash = hashlib.md5(f.read()).hexdigest()

    if file_hash not in hashes:
        hashes.add(file_hash)
        unique_files.append(file)
    else:
        duplicate_count += 1
        print("Duplicate file removed:", file)

print("Total duplicate files removed:", duplicate_count)



Total duplicate files removed: 0


In [ ]:
!ls "/content/drive/MyDrive/MINIPROJECT/yamnet_tf_model_yassen"

ls: cannot access '/content/drive/MyDrive/MINIPROJECT/yamnet_tf_model_yassen': No such file or directory


In [ ]:
import sys
sys.path.append("/content/drive/MyDrive/MINIPROJECT/yamnet_tf_model_yassen")

In [ ]:
import model

In [ ]:
net = model.create_model()
for layer in net.layers:
    layer.trainable = True

In [ ]:
net.load_weights(
"/content/drive/MyDrive/MINIPROJECT/yamnet_tf_model_yassen/weights.h5",
by_name=True,
skip_mismatch=True
)

In [ ]:
net.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 96, 64, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_ (Conv2D)                │ (None, 48, 32, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ b_ (BatchNormalization)         │ (None, 48, 32, 32)     │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_27 (ReLU)                 │ (None, 48, 32, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_               │ (None, 48, 32, 32)     │           320 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L11_ (BatchNormalization)       │ (None, 48, 32, 32)     │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_28 (ReLU)                 │ (None, 48, 32, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1_ (Conv2D)              │ (None, 48, 32, 64)     │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L12_ (BatchNormalization)       │ (None, 48, 32, 64)     │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_29 (ReLU)                 │ (None, 48, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_1_             │ (None, 24, 16, 64)     │           640 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L21_ (BatchNormalization)       │ (None, 24, 16, 64)     │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_30 (ReLU)                 │ (None, 24, 16, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2_ (Conv2D)              │ (None, 24, 16, 128)    │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L22_ (BatchNormalization)       │ (None, 24, 16, 128)    │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_31 (ReLU)                 │ (None, 24, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_2_             │ (None, 24, 16, 128)    │         1,280 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L31_ (BatchNormalization)       │ (None, 24, 16, 128)    │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_32 (ReLU)                 │ (None, 24, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3_ (Conv2D)              │ (None, 24, 16, 128)    │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L32_ (BatchNormalization)       │ (None, 24, 16, 128)    │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_33 (ReLU)                 │ (None, 24, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_3_             │ (None, 12, 8, 128)     │         1,280 │
│ (DepthwiseConv2D)               │                        │             

 Total params: 3,244,357 (12.38 MB)

 Trainable params: 3,222,469 (12.29 MB)

 Non-trainable params: 21,888 (85.50 KB)

In [ ]:
freeze = False

for layer in net.layers:

    if layer.name == "conv2d_12_":
        freeze = True

    if freeze:
        layer.trainable = False

    if layer.name == "fc_new_":
        layer.trainable = True
        freeze = False

In [ ]:
import os
import numpy as np
import librosa
import tensorflow as tf
import tensorflow_hub as hub
from scipy.signal import butter, filtfilt
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split


In [ ]:
def create_linear_fragments(signal):

    spec = np.abs(librosa.stft(
        signal,
        n_fft=128,
        win_length=50,
        hop_length=20
    ))

    spec = np.log1p(spec)

    fragment_frames = 150
    fragments = []

    for start in range(0, spec.shape[1], fragment_frames):

        frag = spec[:, start:start + fragment_frames]

        if frag.shape[1] < fragment_frames:
            pad_width = fragment_frames - frag.shape[1]
            frag = np.pad(frag, ((0,0),(0,pad_width)), mode='constant')

        frag = tf.image.resize(
            frag[..., np.newaxis],
            (96, 64)
        ).numpy()

        frag = frag / np.max(frag)

        fragments.append(frag)

    return fragments

In [ ]:
from scipy.signal import butter, filtfilt
def bandpass_filter(signal, sr, low=25, high=600, order=10):

    nyquist = 0.5 * sr
    low = low / nyquist
    high = high / nyquist

    b, a = butter(order, [low, high], btype='band')

    filtered = filtfilt(b, a, signal)

    return filtered

In [ ]:
def preprocess_signal(path):

    try:
        signal, sr = librosa.load(path, sr=None)
    except Exception as e:

        print("Error loading:", path)
        print(e)
        return None

    print("Loaded:", path)

    if sr != 2000:
        signal = librosa.resample(signal, orig_sr=sr, target_sr=2000)
        sr = 2000

    signal = bandpass_filter(signal, sr)

    std = np.std(signal)

    if std == 0:
        print("STD ZERO:", path)
        return None

    signal = (signal - np.mean(signal)) / std

    duration = len(signal) / sr
    print("Duration:", duration)

    if duration < 1.6:
        print("Too short:", path)
        return None

    if duration > 10:
        signal = signal[:10 * sr]

    return signal.astype(np.float32)

In [ ]:
import os
import numpy as np

def load_dataset(dataset_path):

    X = []
    y = []

    class_names = ["N_New","MR_New","AS_New","MS_New","MVP_New"]

    for label, class_name in enumerate(class_names):

        folder = os.path.join(dataset_path, class_name)

        for file in os.listdir(folder):

            if file.endswith(".wav"):

                path = os.path.join(folder, file)

                signal = preprocess_signal(path)

                if signal is None:
                    continue


                fragments = create_linear_fragments(signal)


                for frag in fragments:
                    X.append(frag)
                    y.append(label)

                if len(X) % 200 == 0:
                    print("Processed:", len(X))

    return np.array(X), np.array(y)

In [ ]:

train_path = "/content/drive/MyDrive/MINIPROJECT/yassen_filtered/train"
test_path  = "/content/drive/MyDrive/MINIPROJECT/yassen_filtered/test"

In [ ]:

X_train, y_train = load_dataset(train_path)
X_test, y_test = load_dataset(test_path)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)




Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_015.wav
Duration: 2.093
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_158.wav
Duration: 2.1015
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_054.wav
Duration: 2.6285
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_086.wav
Duration: 2.5655
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_061.wav
Duration: 2.5965
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_182.wav
Duration: 2.1135
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_027.wav
Duration: 2.117
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_069.wav
Duration: 2.5405
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_017.wav
Duration: 2.064
Loaded: /content/drive/MyDrive/MINIPROJECT/yassen_filtered/train/N_New/New_N_165.wav


In [ ]:
net.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
history = net.fit(
    X_train,
    y_train,
    epochs=40,
    batch_size=32
)

Epoch 1/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 39s 255ms/step - accuracy: 0.2242 - loss: 1.6088
Epoch 2/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.2514 - loss: 1.6070
Epoch 3/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.2984 - loss: 1.6045
Epoch 4/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.3936 - loss: 1.5997
Epoch 5/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5268 - loss: 1.5861
Epoch 6/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5883 - loss: 1.5503
Epoch 7/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6522 - loss: 1.4903
Epoch 8/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.6968 - loss: 1.4205
Epoch 9/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7408 - loss: 1.3435
Epoch 10/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7685 - loss: 1.2718
Epoch 11/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7794 - loss: 1.1998
Epoch 12/40
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accurac

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix, matthews_corrcoef, cohen_kappa_score

y_pred = net.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)


14/14 ━━━━━━━━━━━━━━━━━━━━ 5s 196ms/step


In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[86  0  0  0  0]
 [ 0 78  3  0  6]
 [ 0  1 88  0  1]
 [ 0  0  1 81  3]
 [ 0  1  1  1 83]]


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import cohen_kappa_score
import numpy as np

In [ ]:
from sklearn.metrics import recall_score

uar = recall_score(y_test, y_pred, average='macro')
print(f"Overall Accuracy: {round(accuracy * 100)}%")
print(f"UAR: {uar*100:.2f}")


Overall Accuracy: 96%
UAR: 95.85


In [ ]:
TP = np.diag(cm)
FP = np.sum(cm, axis=0) - TP
FN = np.sum(cm, axis=1) - TP
TN = np.sum(cm) - (TP + FP + FN)

In [ ]:
accuracy = np.sum(TP) / np.sum(cm)

sensitivity = np.mean(TP / (TP + FN))
specificity = np.mean(TN / (TN + FP))

precision = np.mean(TP / (TP + FP))

f1 = np.mean(2 * (precision * sensitivity) / (precision + sensitivity))

snr = np.mean(TP / (FP + 1e-10))

mcc = matthews_corrcoef(y_test, y_pred)

kappa = cohen_kappa_score(y_test, y_pred)

In [ ]:
from sklearn.metrics import recall_score

uar = recall_score(y_test, y_pred, average='macro')
print(f"Overall Accuracy: {round(accuracy * 100)}%")
print(f"UAR: {uar*100:.2f}")


Overall Accuracy: 96%
UAR: 95.85


In [ ]:
print(f"Overall Accuracy: {round(accuracy * 100)}%")
print("Sensitivity:", sensitivity)
print("Specificity:", specificity)
print("Precision:", precision)
print("F1 Score:", f1)
print("SNR:", snr)
print("MCC:", mcc)
print("Kappa:", kappa)

Overall Accuracy: 96%
Sensitivity: 0.9584773914912128
Specificity: 0.9896200931642921
Precision: 0.9603029110936271
F1 Score: 0.95938928289654
SNR: 172000000029.18
MCC: 0.9485140747735151
Kappa: 0.9481488364683862


In [ ]:
net.save("final_model.keras")
from google.colab import files
files.download("final_model.keras")
for i in range(10):
    pred = np.argmax(net.predict(X_val[i:i+1]))
    true = np.argmax(y_val[i])
    print(i, pred, true)